# Generated by Django 5.2.9 on 2025-12-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
