# Generated by Django 5.2.9 on 2025-12-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_professional'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tenantmembership',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
