# Generated by Django 5.2.9 on 2025-12-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='servicedefinition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
